name: Package and Publish
on:
  release:
    types: [published]
jobs:
  package_and_publish:
    name: Package and Publish
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: |
          yarn package        
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish to GitHub
        run: |
          version=$(node -p 'require("./package.json").version')
          yarn publish --registry=https://npm.pkg.github.com dist/js/yetics-armkit-core-${version}.tgz
        working-directory: packages/@armkit/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Reset .npmrc
        run: rm -f ${RUNNER_TEMP}/.npmrc
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM
        run: |
          version=$(node -p 'require("./package.json").version')
          yarn publish --registry=https://registry.npmjs.org dist/js/yetics-armkit-core-${version}.tgz
        working-directory: packages/@armkit/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
