name: Node.js Package
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: |
          yarn package
          cd packages/@armkit/core
          version=$(node -p 'require("./package.json").version')
          yarn publish --registry=https://npm.pkg.github.com ./dist/js/armkit-core-${version}.tgz
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
