name: Mark stale issues and pull requests

on:
  push:
    branches:
      - development

jobs:
  stale:

    runs-on: ubuntu-latest
    container: 'node:current'

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 30
        days-before-close: 5
