# Starter GH Action
name: Build
on:
  # Trigger the workflow on push or pull request,
  # but only for the development branch
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for 'cache-hit'
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.ock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: installing dependencies
        run: |
          yarn install
      - name: compile_armkit_core
        run: |
          cd packages/@armkit/core
          yarn build
      - name: compile_armkit-cli
        run: |
          cd packages/armkit-cli
          yarn build          
      - name: test
        run: |
          cd packages/armkit-cli
          yarn test
      - name: build_examples
        run: |
          cd examples/basic
          yarn generate
          yarn build 
          node index.ts
